### ISSUE TITLE
GPS metadata fields show in Map Viewer Beta but not in Smart Forms or Field Maps

### ISSUE THREAD

**Issue by geotrek** [doug-m/field-maps-testing#27]
### Issue
GPS metadata fields show in Map Viewer Beta but not in Smart Forms or Field Maps
### Expected Behavior
GPS metadata fields should show up as attributes in smart forms and work in field maps app.
I also tried to group attributes in the smart form, but they did not carry over to field maps app

### Map and Credentials

* Group Name:
* Map Name:

### Steps to Reproduce
Use ESRI's Environmental Notes Feature Template, Enable capture GPS metatadata option, create web map in mapViewer beta, save and share, create smart form. GPS metadata fields show in MapViewer but not as attributes in smart forms or in field maps.

### Device Information
Note 10+, Adroid 10

#### Browser (please complete the following information):
Chrome

#### Mobile (please complete the following information):
Note 10+, Adroid 10

### Screenshots

![image](https://user-images.githubusercontent.com/1136532/94176429-f0d9da00-fe4c-11ea-8d36-8079b38fda3c.png)

**Comment by crai3162** [comment]
@geotrek can you go into a bit of detail on how having the GPS Metadata fields available for use in the form?  Is it for informational use for the mobile worker?

**Comment by geotrek** [comment]
Probably information more applicable to GIS admins. Storing [GPS metadata](https://doc.arcgis.com/en/collector-classic/android/create-maps/gps-map-prep.htm#ESRI_SECTION1_22FE236139F649C29E6DF2086DE6912C) can be valuable to assess data quality and ensure data collection standards have been maintained.

@crai3162  These fields are part of the hosted feature service (a feature layer template from ESRI) and show up in the web map viewer so expected them to be configurable in the smart forms and show up in field maps app.

**Comment by crai3162** [comment]
Hi @geotrek they are not available in the Field Maps app and that was an explicit decision; the fact they show up in the Map Viewer could be viewed as an issue with the Map Viewer.  Our mobile apps treat the GPS metadata fields as read-only to the mobile workers and hides the fields.

Even though they are hidden, they will be populated.  But since the mobile apps treats them as read-only for the mobile worker, we don't have a good use case to include as fields that can be used in the form.
