### ISSUE TITLE
Real-time Correction Configuration in App

### ISSUE THREAD

**Issue by BrettFrahm** [doug-m/field-maps-testing#5]
@AmandaHuber

### Describe the solution you'd like
When setting up Location Provider, there is not an option to setup real-correction like there is in Collector

**Additional context**
It is ideal for users to be able to manage everything inside of 1 app. If the intended goal of this product is to make a one-stop shop for field work, then this should definitely be included as an option for people. Have had no issues using it in Collector so I think it should be supported. People can always use their third-party apps to manage GNSS if they prefer.

**Comment by Kevin-GIS** [comment]
@BrettFrahm 

Thank you for the feedback. 

The RTK configuration settings for Trimble receivers is not included within ArcGIS Field Maps in order to leverage the additional configuration capabilities offered by the Trimble Mobile Manager applications for both iOS and Android. 

Some of those capabilities include:
- Defining an accurate Geoid model for specific geographic locations for capturing accurate elevations
- Leveraging time-based geographic transformations for real-time correction sources
